# trade_order { #pygcapi.core_v2.GCapiClientV2.trade_order }

```python
core_v2.GCapiClientV2.trade_order(
    quantity,
    offer_price,
    bid_price,
    direction,
    market_id,
    market_name,
    stop_loss=None,
    take_profit=None,
    trigger_price=None,
    close=False,
    order_id=None,
    tolerance=None,
)
```

Place a trade order.

## Parameters {.doc-section .doc-section-parameters}

| Name          | Type   | Description                               | Default    |
|---------------|--------|-------------------------------------------|------------|
| quantity      | float  | Quantity to trade.                        | _required_ |
| offer_price   | float  | Offer price for the trade.                | _required_ |
| bid_price     | float  | Bid price for the trade.                  | _required_ |
| direction     | str    | Direction of the trade ("buy" or "sell"). | _required_ |
| market_id     | str    | Market ID.                                | _required_ |
| market_name   | str    | Market name.                              | _required_ |
| stop_loss     | float  | Stop loss price (optional).               | `None`     |
| take_profit   | float  | Take profit price (optional).             | `None`     |
| trigger_price | float  | Trigger price (optional).                 | `None`     |
| close         | bool   | Whether to close the trade (optional).    | `False`    |
| order_id      | str    | Order ID (optional).                      | `None`     |
| tolerance     | float  | Price tolerance (optional).               | `None`     |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                   |
|--------|--------|-------------------------------|
|        | dict   | API response as a dictionary. |